# Generated by Django 4.2.2 on 2023-06-24 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('participants_wait', 'Ожидание участников'), ('payment_wait', 'Ожидание оплаты'), ('paid', 'Оплачен'), ('caneled', 'Отменён')], default='participants_wait', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('payment_wait', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('caneled', 'Отменено')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
