# Generated by Django 4.2.2 on 2023-06-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('reply', 'Reply'), ('inline', 'Inline')], default='reply', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('text_ru', models.TextField()),
                ('text_kz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=255)),
                ('text_kz', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('request_contact', models.BooleanField(default=False)),
                ('request_location', models.BooleanField(default=False)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_buttons', to='telegram.keyboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=255)),
                ('text_kz', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('url_ru', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('url_kz', models.URLField(blank=True, default='', max_length=1000, null=True)),
                ('callback_data', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_buttons', to='telegram.keyboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
