# Generated by Django 4.2.2 on 2023-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша'), ('en', 'English')], default='ru', max_length=10),
        ),
    ]
